# Generated by Django 4.0 on 2022-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('ref', models.CharField(max_length=1000)),
                ('genre', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('lang', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=1000)),
            ],
        ),
    ]
